name = "calmiqs-site"
compatibility_date = "2024-11-04"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "CALMIQS_POSTS"
id = "7bceea0c0fe9419b81c41b54231acc11"

[[kv_namespaces]]
binding = "CALMIQS_IMAGES"
id = "cdab54f42fde47db8ea06123a7b686eb"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "calmiqs-images"

