name = "calmiqs-site"
main = "./functions"

[env.production]
kv_namespaces = [
  { binding = "CALMIQS_POSTS", id = "7bceea0c0fe9419b81c41b54231acc11" }
]

pages_build_output_dir = "public"

# For images (new one)
wrangler kv:namespace create "CALMIQS_IMAGES"

